### ISSUE TITLE
column_id is NULL for CUSTOM_SQL_STATEMENT rules in summary table

### ISSUE THREAD

**Issue by tooobsias** [GoogleCloudPlatform/cloud-data-quality#122]
For rules of type 'CUSTOM_SQL_STATEMENT', the corresponding column_id in the summary table is null.

Is this a desired behaviour ?

**Comment by thinhha** [comment]
Hi there, thanks for trying CloudDQ and leaving feedback. 

TL;DR it is intended.
Custom SQL statement rules can technically validate multiple columns (as is the case with the duplicate check right) or any column not referenced in the rule binding, hence why column id is set to null.

**Comment by tooobsias** [comment]
Hi @thinhha, thanks for the quick clarification.

The use-case we want to archive is to have more generic custom tests, especially with [multiple] input parameters while still be able to see the corresponding column in the summary results.

One possible test for checking if values are between are specific range is e.g:

```yaml
  CUSTOM_SQL_LENGTH_BETWEEN:  
      rule_type: CUSTOM_SQL_STATEMENT 
      dimension: correctness  
      params:  
        custom_sql_arguments:  
          - min  
          - max
        custom_sql_statement: |-  
          SELECT $column  
          FROM data  
          WHERE LENGTH($column) >= $min AND LENGTH($column) <= $max
```

This is currently not possible with the CUSTOM_SQL_EXPR rule type, as it does not allow for any custom_sql_arguments.
However, with the CUSTOM_SQL_EXPR the corresponding column is referenced in the summary result.

Would one possible solution be, to add arguments to the CUSTOM_SQL_EXPR rule type as well ?
