### ISSUE TITLE
Allow environment variables substitition in yaml files

### ISSUE THREAD

**Issue by Luiscri** [GoogleCloudPlatform/cloud-data-quality#220]
It would be useful if environment variables substitution were allowed for yaml files. An usage example would be refering to a different table according to the environment we are:

``` yml
entities:
  MY_TABLE:
    source_database: BIGQUERY
    table_name: ${GOOGLE_CLOUD_PROJECT}.mydataset.mytable
...

# or

entities:
  MY_TABLE:
    entity_uri: bigquery://projects/${GOOGLE_CLOUD_PROJECT}/datasets/mydataset/tables/mytable
...
```
