### ISSUE TITLE
Implement tagging for rule binding and tags execution

### ISSUE THREAD

**Issue by Luiscri** [GoogleCloudPlatform/cloud-data-quality#253]
It would be really helpful if we could tag the rule bindings, and then execute the DQ checks for those tagged rule bindings only, similar to how it's done in dbt. Something like:

```
rule_bindings:
    my_rule_binding:
        tags: ["weekly"]
...
```

and then:

```
python3 clouddq_executable.zip tag:weekly ...
```

Would this be something easy to implement?
